##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  Fri Oct 10 00:56:52 2014
##  Generated by MIG Version 2.2
##
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K325T-FFG900
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8JTF12864HZ-1G6
## Data Width: 64
## Time Period: 1250
## Data Mask: 1
##################################################################################################

#set_property BITSTREAM.CONFIG.BPI_SYNC_MODE Type2 [current_design]
#set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-2 [current_design]
#set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
#set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
#set_property CONFIG_MODE BPI16 [current_design]
#set_property CFGBVS VCCO [current_design]
#set_property CONFIG_VOLTAGE 2.5 [current_design]

# Set DCI_CASCADE
#set_property slave_banks {32 34} [get_iobanks 33]
############## NET - IOSTANDARD ##################
# Bank: 33 - GPIO_SW_S (CPU_RESET)
set_property VCCAUX_IO DONTCARE [get_ports sys_rst]
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst]
set_property PACKAGE_PIN AB12 [get_ports sys_rst]

#kc705 system_clk  system_rst

# Bank: 33 - GPIO_LED_0_LS
#set_property DRIVE 12 [get_ports {led[0]}]
#set_property SLEW SLOW [get_ports {led[0]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[0]}]
#set_property LOC AB8 [get_ports {led[0]}]

# Bank: 33 - GPIO_LED_1_LS
#set_property DRIVE 12 [get_ports {led[1]}]
#set_property SLEW SLOW [get_ports {led[1]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
#set_property LOC AA8 [get_ports {led[1]}]

# Bank: 33 - GPIO_LED_2_LS
#set_property DRIVE 12 [get_ports {led[2]}]
#set_property SLEW SLOW [get_ports {led[2]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[2]}]
#set_property LOC AC9 [get_ports {led[2]}]

# Bank: 33 - GPIO_LED_3_LS
#set_property DRIVE 12 [get_ports {led[3]}]
#set_property SLEW SLOW [get_ports {led[3]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]
#set_property LOC AB9 [get_ports {led[3]}]

#uart
set_property PACKAGE_PIN M19 [get_ports uart_sin]
set_property IOSTANDARD LVCMOS25 [get_ports uart_sin]
set_property PACKAGE_PIN K24 [get_ports uart_sout]
set_property IOSTANDARD LVCMOS25 [get_ports uart_sout]

#以太网
set_property PACKAGE_PIN R23 [get_ports mdio_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_mdc]
set_property PACKAGE_PIN J21 [get_ports mdio_mdio]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_mdio]

#phy_clk
#create_clock -period 1.600 -name phy_clk [get_ports phy_clk_p]

#phy_rst
set_property PACKAGE_PIN L20 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rst_n]

set_property PACKAGE_PIN H5 [get_ports phy_rx_n]
set_property PACKAGE_PIN H6 [get_ports phy_rx_p]
set_property PACKAGE_PIN J3 [get_ports phy_tx_n]
set_property PACKAGE_PIN J4 [get_ports phy_tx_p]
set_property PACKAGE_PIN G7 [get_ports phy_clk_n]
set_property PACKAGE_PIN G8 [get_ports phy_clk_p]

set_property IOSTANDARD LVDS_25 [get_ports phy_rx_n]
set_property IOSTANDARD LVDS_25 [get_ports phy_rx_p]
set_property IOSTANDARD LVDS_25 [get_ports phy_tx_n]
set_property IOSTANDARD LVDS_25 [get_ports phy_tx_p]
set_property IOSTANDARD LVDS_25 [get_ports phy_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports phy_clk_p]




#fan_pwm
set_property PACKAGE_PIN L26 [get_ports fan_pwm]
set_property IOSTANDARD LVCMOS25 [get_ports fan_pwm]

#以上都是以太网

#iic
set_property PACKAGE_PIN K21 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS25 [get_ports iic_scl]
set_property PACKAGE_PIN L21 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS25 [get_ports iic_sda]

#主要部分
set_property -dict {PACKAGE_PIN C8} [get_ports ref_clk0_p]
set_property -dict {PACKAGE_PIN C7} [get_ports ref_clk0_n]
set_property -dict {PACKAGE_PIN E8} [get_ports ref_clk1_p]
set_property -dict {PACKAGE_PIN E7} [get_ports ref_clk1_n]

set_property -dict {PACKAGE_PIN D6} [get_ports {rx_data_p[0]}]
set_property -dict {PACKAGE_PIN D5} [get_ports {rx_data_n[0]}]
set_property -dict {PACKAGE_PIN B6} [get_ports {rx_data_p[1]}]
set_property -dict {PACKAGE_PIN B5} [get_ports {rx_data_n[1]}]
set_property -dict {PACKAGE_PIN E4} [get_ports {rx_data_p[2]}]
set_property -dict {PACKAGE_PIN E3} [get_ports {rx_data_n[2]}]
set_property -dict {PACKAGE_PIN A8} [get_ports {rx_data_p[3]}]
set_property -dict {PACKAGE_PIN A7} [get_ports {rx_data_n[3]}]

set_property -dict {PACKAGE_PIN B2} [get_ports {tx_data_p[0]}]
set_property -dict {PACKAGE_PIN B1} [get_ports {tx_data_n[0]}]
set_property -dict {PACKAGE_PIN D2} [get_ports {tx_data_p[1]}]
set_property -dict {PACKAGE_PIN D1} [get_ports {tx_data_n[1]}]
set_property -dict {PACKAGE_PIN A4} [get_ports {tx_data_p[2]}]
set_property -dict {PACKAGE_PIN A3} [get_ports {tx_data_n[2]}]
set_property -dict {PACKAGE_PIN C4} [get_ports {tx_data_p[3]}]
set_property -dict {PACKAGE_PIN C3} [get_ports {tx_data_n[3]}]

# ad9371
set_property IOSTANDARD LVDS_25 [get_ports rx_sync_n]
set_property PACKAGE_PIN H27 [get_ports rx_sync_n]
set_property PACKAGE_PIN H26 [get_ports rx_sync_p]
set_property IOSTANDARD LVDS_25 [get_ports rx_sync_p]

set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVDS_25} [get_ports rx_os_sync_p]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVDS_25} [get_ports rx_os_sync_n]


set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVDS_25} [get_ports tx_sync_p]
set_property -dict {PACKAGE_PIN H25 IOSTANDARD LVDS_25} [get_ports tx_sync_n]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVDS_25} [get_ports sysref_p]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVDS_25} [get_ports sysref_n]

#spi
set_property -dict {PACKAGE_PIN A30 IOSTANDARD LVCMOS25} [get_ports spi_csn_ad9528]
set_property -dict {PACKAGE_PIN B30 IOSTANDARD LVCMOS25} [get_ports spi_csn_ad9371]
set_property -dict {PACKAGE_PIN E28 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN D28 IOSTANDARD LVCMOS25} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVCMOS25} [get_ports spi_miso]


#set_property PACKAGE_PIN E29 [get_ports spi_miso]                                                    ; ## G12  FMC_HPC_LA08_P
#set_property IOSTANDARD LVCMOS25 [get_ports spi_miso]


set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS25} [get_ports ad9528_reset_b]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS25} [get_ports ad9528_sysref_req]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD LVCMOS25} [get_ports ad9371_tx1_enable]
set_property -dict {PACKAGE_PIN B28 IOSTANDARD LVCMOS25} [get_ports ad9371_tx2_enable]
set_property -dict {PACKAGE_PIN A26 IOSTANDARD LVCMOS25} [get_ports ad9371_rx1_enable]
set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVCMOS25} [get_ports ad9371_rx2_enable]
set_property -dict {PACKAGE_PIN G29 IOSTANDARD LVCMOS25} [get_ports ad9371_test]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS25} [get_ports ad9371_reset_b]
set_property -dict {PACKAGE_PIN F28 IOSTANDARD LVCMOS25} [get_ports ad9371_gpint]

#GPIO
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_00]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_01]
set_property -dict {PACKAGE_PIN B27 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_02]
set_property -dict {PACKAGE_PIN A27 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_03]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_04]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_05]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_06]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_07]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_15]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_08]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_09]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_10]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_11]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_12]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_14]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_13]
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_17]
set_property -dict {PACKAGE_PIN B29 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_16]
set_property -dict {PACKAGE_PIN F30 IOSTANDARD LVCMOS25} [get_ports ad9371_gpio_18]

# gpio (switches, leds and such)
set_property -dict {PACKAGE_PIN Y29 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[0]}]
set_property -dict {PACKAGE_PIN W29 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[1]}]
set_property -dict {PACKAGE_PIN AA28 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[2]}]
set_property -dict {PACKAGE_PIN Y28 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[3]}]

#GPIO_SW
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS15 DRIVE 8} [get_ports {gpio_bd[4]}]
set_property -dict {PACKAGE_PIN AG5 IOSTANDARD LVCMOS15 DRIVE 8} [get_ports {gpio_bd[5]}]
set_property -dict {PACKAGE_PIN AC6 IOSTANDARD LVCMOS15 DRIVE 8} [get_ports {gpio_bd[7]}]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS25 DRIVE 8} [get_ports {gpio_bd[8]}]

#GPIO_LED
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[9]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[10]}]
set_property -dict {PACKAGE_PIN AC9 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[11]}]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[12]}]
set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[13]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[14]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[15]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[16]}]


#XADC_GPIO
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[17]}]
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[18]}]
set_property -dict {PACKAGE_PIN AB28 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[19]}]
set_property -dict {PACKAGE_PIN AA27 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[20]}]



# PadFunction: IO_L20P_T3_32

# PadFunction: IO_L23N_T3_32

# PadFunction: IO_L22P_T3_32

# PadFunction: IO_L22N_T3_32

# PadFunction: IO_L23P_T3_32

# PadFunction: IO_L20N_T3_32

# PadFunction: IO_L19P_T3_32

# PadFunction: IO_L24N_T3_32

# PadFunction: IO_L17P_T2_32

# PadFunction: IO_L14N_T2_SRCC_32

# PadFunction: IO_L17N_T2_32

# PadFunction: IO_L14P_T2_SRCC_32

# PadFunction: IO_L16P_T2_32

# PadFunction: IO_L16N_T2_32

# PadFunction: IO_L13N_T2_MRCC_32

# PadFunction: IO_L13P_T2_MRCC_32

# PadFunction: IO_L8P_T1_32

# PadFunction: IO_L7N_T1_32

# PadFunction: IO_L11N_T1_SRCC_32

# PadFunction: IO_L11P_T1_SRCC_32

# PadFunction: IO_L8N_T1_32

# PadFunction: IO_L7P_T1_32

# PadFunction: IO_L10N_T1_32

# PadFunction: IO_L10P_T1_32

# PadFunction: IO_L1P_T0_32

# PadFunction: IO_L5N_T0_32

# PadFunction: IO_L2P_T0_32

# PadFunction: IO_L4P_T0_32

# PadFunction: IO_L5P_T0_32

# PadFunction: IO_L4N_T0_32

# PadFunction: IO_L2N_T0_32

# PadFunction: IO_L1N_T0_32

# PadFunction: IO_L23N_T3_34

# PadFunction: IO_L22N_T3_34

# PadFunction: IO_L20N_T3_34

# PadFunction: IO_L20P_T3_34

# PadFunction: IO_L19P_T3_34

# PadFunction: IO_L24N_T3_34

# PadFunction: IO_L23P_T3_34

# PadFunction: IO_L22P_T3_34

# PadFunction: IO_L14N_T2_SRCC_34

# PadFunction: IO_L14P_T2_SRCC_34

# PadFunction: IO_L16N_T2_34

# PadFunction: IO_L16P_T2_34

# PadFunction: IO_L13P_T2_MRCC_34

# PadFunction: IO_L13N_T2_MRCC_34

# PadFunction: IO_L17N_T2_34

# PadFunction: IO_L17P_T2_34

# PadFunction: IO_L8N_T1_34

# PadFunction: IO_L7N_T1_34

# PadFunction: IO_L10P_T1_34

# PadFunction: IO_L10N_T1_34

# PadFunction: IO_L7P_T1_34

# PadFunction: IO_L11N_T1_SRCC_34

# PadFunction: IO_L8P_T1_34

# PadFunction: IO_L11P_T1_SRCC_34

# PadFunction: IO_L2N_T0_34

# PadFunction: IO_L1N_T0_34

# PadFunction: IO_L4N_T0_34

# PadFunction: IO_L4P_T0_34

# PadFunction: IO_L5N_T0_34

# PadFunction: IO_L5P_T0_34

# PadFunction: IO_L2P_T0_34

# PadFunction: IO_L1P_T0_34

# PadFunction: IO_L18P_T2_33

# PadFunction: IO_L18N_T2_33

# PadFunction: IO_L19P_T3_33

# PadFunction: IO_L19N_T3_VREF_33

# PadFunction: IO_L20P_T3_33

# PadFunction: IO_L20N_T3_33

# PadFunction: IO_L21P_T3_DQS_33

# PadFunction: IO_L21N_T3_DQS_33

# PadFunction: IO_L22P_T3_33

# PadFunction: IO_L22N_T3_33

# PadFunction: IO_L23P_T3_33

# PadFunction: IO_L23N_T3_33

# PadFunction: IO_L24P_T3_33

# PadFunction: IO_L24N_T3_33

# PadFunction: IO_L15N_T2_DQS_33

# PadFunction: IO_L16P_T2_33

# PadFunction: IO_L16N_T2_33

# PadFunction: IO_L10P_T1_33

# PadFunction: IO_L9N_T1_DQS_33

# PadFunction: IO_L10N_T1_33

# PadFunction: IO_L18N_T2_34

# PadFunction: IO_L14N_T2_SRCC_33

# PadFunction: IO_L8P_T1_33

# PadFunction: IO_L9P_T1_DQS_33

# PadFunction: IO_L24P_T3_32

# PadFunction: IO_L18P_T2_32

# PadFunction: IO_L12P_T1_MRCC_32

# PadFunction: IO_L6P_T0_32

# PadFunction: IO_L24P_T3_34

# PadFunction: IO_L18P_T2_34

# PadFunction: IO_L12P_T1_MRCC_34

# PadFunction: IO_L6P_T0_34

# PadFunction: IO_L12P_T1_MRCC_33
#set_property VCCAUX_IO DONTCARE [get_ports sys_clk_p]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]

## PadFunction: IO_L12N_T1_MRCC_33
#set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_n]
#set_property PACKAGE_PIN AD11 [get_ports sys_clk_n]
#set_property PACKAGE_PIN AD12 [get_ports sys_clk_p]

set_property PACKAGE_PIN AD11 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS [get_ports sys_clk_n]
set_property PACKAGE_PIN AD12 [get_ports sys_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]

# PadFunction: IO_L21P_T3_DQS_32

# PadFunction: IO_L21N_T3_DQS_32

# PadFunction: IO_L15P_T2_DQS_32

# PadFunction: IO_L15N_T2_DQS_32

# PadFunction: IO_L9P_T1_DQS_32

# PadFunction: IO_L9N_T1_DQS_32

# PadFunction: IO_L3P_T0_DQS_32

# PadFunction: IO_L3N_T0_DQS_32

# PadFunction: IO_L21P_T3_DQS_34

# PadFunction: IO_L21N_T3_DQS_34

# PadFunction: IO_L15P_T2_DQS_34

# PadFunction: IO_L15N_T2_DQS_34

# PadFunction: IO_L9P_T1_DQS_34

# PadFunction: IO_L9N_T1_DQS_34

# PadFunction: IO_L3P_T0_DQS_34

# PadFunction: IO_L3N_T0_DQS_34

# PadFunction: IO_L13P_T2_MRCC_33

# PadFunction: IO_L13N_T2_MRCC_33
