# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ad9371.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_cntlr_0 || ORIG_REF_NAME==system_sys_dlmb_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_cntlr_0 || ORIG_REF_NAME==system_sys_ilmb_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_rstgen_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_ethernet_0/bd_0/bd_55cd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd || ORIG_REF_NAME==bd_55cd} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_eth_buf_0 || ORIG_REF_NAME==bd_55cd_eth_buf_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/bd_55cd_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_mac_0 || ORIG_REF_NAME==bd_55cd_mac_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/bd_55cd_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_pcs_pma_0 || ORIG_REF_NAME==bd_55cd_pcs_pma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_3/bd_55cd_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_55cd_xlconstant_phyadd_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_4/bd_55cd_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_c_shift_ram_0_0 || ORIG_REF_NAME==bd_55cd_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_5/bd_55cd_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_c_counter_binary_0_0 || ORIG_REF_NAME==bd_55cd_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_6/bd_55cd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_xlconstant_0_0 || ORIG_REF_NAME==bd_55cd_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_7/bd_55cd_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_util_vector_logic_0_0 || ORIG_REF_NAME==bd_55cd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_dma_0 || ORIG_REF_NAME==system_axi_ethernet_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_timer_0/system_axi_timer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0 || ORIG_REF_NAME==system_axi_timer_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_interconnect_0/system_axi_mem_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_interconnect_0 || ORIG_REF_NAME==system_axi_mem_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_dacfifo_0/system_axi_ad9371_dacfifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_dacfifo_0 || ORIG_REF_NAME==system_axi_ad9371_dacfifo_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_tx_clkgen_0/system_axi_ad9371_tx_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_clkgen_0 || ORIG_REF_NAME==system_axi_ad9371_tx_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_tx_xcvr_0/system_axi_ad9371_tx_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_xcvr_0 || ORIG_REF_NAME==system_axi_ad9371_tx_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9371_tx_upack_0/system_util_ad9371_tx_upack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9371_tx_upack_0 || ORIG_REF_NAME==system_util_ad9371_tx_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_tx_dma_0/system_axi_ad9371_tx_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_dma_0 || ORIG_REF_NAME==system_axi_ad9371_tx_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_clkgen_0/system_axi_ad9371_rx_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_clkgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_xcvr_0/system_axi_ad9371_rx_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_xcvr_0 || ORIG_REF_NAME==system_axi_ad9371_rx_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9371_rx_cpack_0/system_util_ad9371_rx_cpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9371_rx_cpack_0 || ORIG_REF_NAME==system_util_ad9371_rx_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_dma_0/system_axi_ad9371_rx_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_dma_0 || ORIG_REF_NAME==system_axi_ad9371_rx_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_os_clkgen_0/system_axi_ad9371_rx_os_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_clkgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_os_xcvr_0/system_axi_ad9371_rx_os_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_xcvr_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9371_rx_os_cpack_0/system_util_ad9371_rx_os_cpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9371_rx_os_cpack_0 || ORIG_REF_NAME==system_util_ad9371_rx_os_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_os_dma_0/system_axi_ad9371_rx_os_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_dma_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_core_0/system_axi_ad9371_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_core_0 || ORIG_REF_NAME==system_axi_ad9371_core_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9371_xcvr_0/system_util_ad9371_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9371_xcvr_0 || ORIG_REF_NAME==system_util_ad9371_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_tx_jesd_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_jesd_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_jesd_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dma_rstgen_0 || ORIG_REF_NAME==system_sys_dma_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_1/system_rx_axi_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_axi_1 || ORIG_REF_NAME==system_rx_axi_1} -quiet] -quiet

# IP: bd/system/ip/system_rx_1/system_rx_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_1 || ORIG_REF_NAME==system_rx_1} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_0/system_rx_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_0/system_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_axi_0/system_tx_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tx_axi_0 || ORIG_REF_NAME==system_tx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_0/system_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tx_0 || ORIG_REF_NAME==system_tx_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_1 || ORIG_REF_NAME==system_mig_7series_0_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_2 || ORIG_REF_NAME==system_auto_us_cc_df_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_1 || ORIG_REF_NAME==system_auto_us_cc_df_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_0 || ORIG_REF_NAME==system_auto_us_cc_df_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_6/system_auto_us_df_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_6 || ORIG_REF_NAME==system_auto_us_df_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_5/system_auto_us_df_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_5 || ORIG_REF_NAME==system_auto_us_df_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_4/system_auto_us_df_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_4 || ORIG_REF_NAME==system_auto_us_df_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_3/system_auto_us_df_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_3 || ORIG_REF_NAME==system_auto_us_df_3} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_2/system_auto_us_df_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_2 || ORIG_REF_NAME==system_auto_us_df_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_1 || ORIG_REF_NAME==system_auto_us_df_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_0 || ORIG_REF_NAME==system_auto_us_df_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc_debug.xdc

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc_trace.xdc

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_rstgen_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_rstgen_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_buf_0 || ORIG_REF_NAME==bd_55cd_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_55cd_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_buf_0 || ORIG_REF_NAME==bd_55cd_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_mac_0 || ORIG_REF_NAME==bd_55cd_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_mac_0 || ORIG_REF_NAME==bd_55cd_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_mac_0 || ORIG_REF_NAME==bd_55cd_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/bd_55cd_pcs_pma_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_pcs_pma_0 || ORIG_REF_NAME==bd_55cd_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_pcs_pma_0 || ORIG_REF_NAME==bd_55cd_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_4/bd_55cd_c_shift_ram_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_5/bd_55cd_c_counter_binary_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/bd_55cd_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_0/synth/system_axi_ethernet_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ethernet_dma_0 || ORIG_REF_NAME==system_axi_ethernet_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ethernet_dma_0 || ORIG_REF_NAME==system_axi_ethernet_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_timer_0/system_axi_timer_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_timer_0 || ORIG_REF_NAME==system_axi_timer_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_timer_0/system_axi_timer_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ad9371_dacfifo_0/util_dacfifo_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_dacfifo_0 || ORIG_REF_NAME==system_axi_ad9371_dacfifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# TCL: bd/system/ip/system_axi_ad9371_tx_clkgen_0/bd/bd.tcl

# TCL: bd/system/ip/system_axi_ad9371_tx_dma_0/bd/bd.tcl

# XDC: bd/system/ip/system_axi_ad9371_tx_dma_0/system_axi_ad9371_tx_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_dma_0 || ORIG_REF_NAME==system_axi_ad9371_tx_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# TCL: bd/system/ip/system_axi_ad9371_rx_clkgen_0/bd/bd.tcl

# TCL: bd/system/ip/system_axi_ad9371_rx_dma_0/bd/bd.tcl

# XDC: bd/system/ip/system_axi_ad9371_rx_dma_0/system_axi_ad9371_rx_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_dma_0 || ORIG_REF_NAME==system_axi_ad9371_rx_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# TCL: bd/system/ip/system_axi_ad9371_rx_os_clkgen_0/bd/bd.tcl

# TCL: bd/system/ip/system_axi_ad9371_rx_os_dma_0/bd/bd.tcl

# XDC: bd/system/ip/system_axi_ad9371_rx_os_dma_0/system_axi_ad9371_rx_os_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_dma_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/up_xfer_status_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/ad_rst_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# XDC: bd/system/ip/system_util_ad9371_xcvr_0/util_adxcvr_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9371_xcvr_0 || ORIG_REF_NAME==system_util_ad9371_xcvr_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_tx_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_tx_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_tx_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9371_rx_os_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9371_rx_os_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_dma_rstgen_0 || ORIG_REF_NAME==system_sys_dma_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_dma_rstgen_0 || ORIG_REF_NAME==system_sys_dma_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_rx_axi_1/axi_jesd204_rx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_1 || ORIG_REF_NAME==system_rx_axi_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/ip/system_rx_1/jesd204_rx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_1 || ORIG_REF_NAME==system_rx_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/ip/system_rx_0/jesd204_rx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_tx_axi_0 || ORIG_REF_NAME==system_tx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/ip/system_tx_0/jesd204_tx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_tx_0 || ORIG_REF_NAME==system_tx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/constraints/system_mig_7series_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_1 || ORIG_REF_NAME==system_mig_7series_0_1} -quiet] -quiet

# XDC: bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/constraints/system_mig_7series_0_1_ooc.xdc

# XDC: bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_1 || ORIG_REF_NAME==system_mig_7series_0_1} -quiet] -quiet

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_2 || ORIG_REF_NAME==system_auto_us_cc_df_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_1 || ORIG_REF_NAME==system_auto_us_cc_df_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_cc_df_0 || ORIG_REF_NAME==system_auto_us_cc_df_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_6 || ORIG_REF_NAME==system_auto_us_df_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_5 || ORIG_REF_NAME==system_auto_us_df_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_4 || ORIG_REF_NAME==system_auto_us_df_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_3 || ORIG_REF_NAME==system_auto_us_df_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_2 || ORIG_REF_NAME==system_auto_us_df_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_1 || ORIG_REF_NAME==system_auto_us_df_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_0 || ORIG_REF_NAME==system_auto_us_df_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
