# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -ruleid {2}  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -ruleid {22}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {23}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {3}  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -ruleid {4}  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -ruleid {5}  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -ruleid {9}  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.cache/wt [current_project]
set_property parent.project_path E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.5 [current_project]
set_property ip_repo_paths e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/library [current_project]
set_property ip_output_repo e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/library/xilinx/common/ad_iobuf.v
  E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/hdl/system_wrapper.v
  E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/system_top.v
}
add_files E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_rstgen_0/system_axi_ddr_cntrl_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_55cd_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/bd_55cd_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_4/bd_55cd_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_5/bd_55cd_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/bd_55cd_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/synth/system_axi_ethernet_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_timer_0/system_axi_timer_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_timer_0/system_axi_timer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_dacfifo_0/util_dacfifo_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_tx_dma_0/system_axi_ad9371_tx_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_dma_0/system_axi_ad9371_rx_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_os_dma_0/system_axi_ad9371_rx_os_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_util_ad9371_xcvr_0/util_adxcvr_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/system_axi_ad9371_tx_jesd_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/system_axi_ad9371_rx_jesd_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/system_axi_ad9371_rx_os_jesd_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_sys_dma_rstgen_0/system_sys_dma_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_rx_axi_1/axi_jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_rx_1/jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_rx_0/jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_tx_0/jesd204_tx_constr.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/constraints/system_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/constraints/system_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1_board.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_2/system_auto_us_cc_df_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_1/system_auto_us_cc_df_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_cc_df_0/system_auto_us_cc_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/constrs_1/new/ad9371.xdc
set_property used_in_implementation false [get_files E:/vivado2017.4/KC705/AD9371/hdl-hdl_2018_r1/projects/adrv9371x/kc705/adrv9371x_kc705.srcs/constrs_1/new/ad9371.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_top -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
