#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4.1 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Oct 10 20:35:11 +0800 2018
# SW Build 2117270 on Tue Jan 30 15:32:00 MST 2018
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm microblaze_v10_0_5 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_14 axi_lite_ipif_v3_0_4 mdm_v3_2_12 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 fifo_generator_v13_2_1 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 axi_ethernet_buffer_v2_0_17 xbip_utils_v3_0_8 xbip_pipe_v3_0_4 xbip_bram18k_v3_0_4 mult_gen_v12_0_13 tri_mode_ethernet_mac_v9_0_10 gig_ethernet_pcs_pma_v16_1_2 xlconstant_v1_1_3 c_reg_fd_v12_0_4 c_mux_bit_v12_0_4 c_shift_ram_v12_0_11 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_4 xbip_addsub_v3_0_4 c_addsub_v12_0_11 c_gate_bit_v12_0_4 xbip_counter_v3_0_4 c_counter_binary_v12_0_11 util_vector_logic_v2_0_1 lib_pkg_v1_0_2 lib_fifo_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_17 axi_sg_v4_1_8 axi_dma_v7_1_16 interrupt_control_v3_1_4 axi_iic_v2_0_18 axi_uartlite_v2_0_19 axi_timer_v2_0_17 dist_mem_gen_v8_0_12 axi_quad_spi_v3_2_14 axi_gpio_v2_0_17 axi_intc_v4_1_10 xlconcat_v2_1_1 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_15 axi_data_fifo_v2_1_14 axi_crossbar_v2_1_16 axi_clock_converter_v2_1_14 axi_protocol_converter_v2_1_15 axi_dwidth_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2017.4.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "D:/vivado2017.4/install/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/vivado2017.4/install/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/vivado2017.4/install/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/vivado2017.4/install/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_5 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/4f30/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_mb_0/sim/system_sys_mb_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_dlmb_0/sim/system_sys_dlmb_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_sys_ilmb_0/sim/system_sys_ilmb_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/226d/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_dlmb_cntlr_0/sim/system_sys_dlmb_cntlr_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_sys_ilmb_cntlr_0/sim/system_sys_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_12 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/8608/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_mb_debug_0/sim/system_sys_mb_debug_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_ddr_cntrl_rstgen_0/sim/system_axi_ddr_cntrl_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernet_buffer_v2_0_17 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/c76a/hdl/axi_ethernet_buffer_v2_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/sim/bd_55cd_eth_buf_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_8 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/4173/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ee5e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/9eb4/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/257f/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work tri_mode_ethernet_mac_v9_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/5fca/hdl/tri_mode_ethernet_mac_v9_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work tri_mode_ethernet_mac_v9_0_10 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/5fca/hdl/tri_mode_ethernet_mac_v9_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/common/bd_55cd_mac_0_block_sync_block.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_axi4_lite_ipif_top.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_axi4_lite_ipif_wrapper.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/statistics/bd_55cd_mac_0_vector_decode.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_block.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work gig_ethernet_pcs_pma_v16_1_2 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/d8c8/hdl/gig_ethernet_pcs_pma_v16_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gig_ethernet_pcs_pma_v16_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/d8c8/hdl/gig_ethernet_pcs_pma_v16_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_sgmii_phy_clk_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_sgmii_phy_reset_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_idelayctrl.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_support.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_reset_wtd_timer.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_adapt/bd_55cd_pcs_pma_0_clk_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_adapt/bd_55cd_pcs_pma_0_johnson_cntr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_reset_sync.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_adapt/bd_55cd_pcs_pma_0_rx_rate_adapt.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_adapt/bd_55cd_pcs_pma_0_sgmii_adapt.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_sync_block.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_adapt/bd_55cd_pcs_pma_0_tx_rate_adapt.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_gearbox_10b_6b.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_gearbox_6b_10b.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_sgmii_eye_monitor.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_sgmii_phy_calibration.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_sgmii_comma_alignment.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_lvds_transceiver/bd_55cd_pcs_pma_0_decode_8b10b_lut_base.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/sgmii_lvds_transceiver/bd_55cd_pcs_pma_0_encode_8b10b_lut_base.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_sgmii_phy_iob.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_gpio_sgmii_top.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/lvds_transceiver/bd_55cd_pcs_pma_0_lvds_transceiver.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0_block.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_2/synth/bd_55cd_pcs_pma_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_3/sim/bd_55cd_xlconstant_phyadd_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/e6f0/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/660b/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/7c1c/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_4/sim/bd_55cd_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/7b8d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/c060/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/1607/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/4b95/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/df83/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ffc8/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_5/sim/bd_55cd_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_6/sim/bd_55cd_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_7/sim/bd_55cd_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/bd_0/sim/bd_55cd.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_0/sim/system_axi_ethernet_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_17 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_8 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/5f94/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_16 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/bf8c/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ethernet_dma_0/sim/system_axi_ethernet_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_18 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/4185/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_iic_main_0/sim/system_axi_iic_main_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/c778/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_uart_0/sim/system_axi_uart_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_17 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/38c3/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_timer_0/sim/system_axi_timer_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/d46a/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_quad_spi_v3_2_14 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/9db7/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_spi_0/sim/system_axi_spi_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_17 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/c450/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0/sim/system_axi_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/cf04/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_intc_0/sim/system_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_sys_concat_intc_0/sim/system_sys_concat_intc_0.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_b2g.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_g2b.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/b972/util_dacfifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_dacfifo_0/sim/system_axi_ad9371_dacfifo_0.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/ad_mmcm_drp.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_rst.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_axi.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_clkgen.v" \
    "$ref_dir/../../../bd/system/ipshared/af2d/axi_clkgen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_tx_clkgen_0/sim/system_axi_ad9371_tx_clkgen_0.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_es.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_mdrp.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_mstatus.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_up.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_tx_xcvr_0/sim/system_axi_ad9371_tx_xcvr_0.v" \
    "$ref_dir/../../../bd/system/ipshared/60ce/util_upack_dmx.v" \
    "$ref_dir/../../../bd/system/ipshared/60ce/util_upack_dsf.v" \
    "$ref_dir/../../../bd/system/ipshared/60ce/util_upack.v" \
    "$ref_dir/../../../bd/system/ip/system_util_ad9371_tx_upack_0/sim/system_util_ad9371_tx_upack_0.v" \
    "$ref_dir/../../../bd/system/ipshared/3d7b/util_axis_resize.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_bits.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_data.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_event.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_gray.v" \
    "$ref_dir/../../../bd/system/ipshared/0d03/address_gray_pipelined.v" \
    "$ref_dir/../../../bd/system/ipshared/0d03/address_sync.v" \
    "$ref_dir/../../../bd/system/ipshared/0d03/util_axis_fifo.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/2d_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/address_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_register_slice.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/data_mover.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/dest_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/dest_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/dest_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/request_arb.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/request_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/response_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/response_handler.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/splitter.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/src_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/src_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/src_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_tx_dma_0/sim/system_axi_ad9371_tx_dma_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_clkgen_0/sim/system_axi_ad9371_rx_clkgen_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_xcvr_0/sim/system_axi_ad9371_rx_xcvr_0.v" \
    "$ref_dir/../../../bd/system/ipshared/2884/util_cpack_dsf.v" \
    "$ref_dir/../../../bd/system/ipshared/2884/util_cpack_mux.v" \
    "$ref_dir/../../../bd/system/ipshared/2884/util_cpack.v" \
    "$ref_dir/../../../bd/system/ip/system_util_ad9371_rx_cpack_0/sim/system_util_ad9371_rx_cpack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_dma_0/sim/system_axi_ad9371_rx_dma_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_os_clkgen_0/sim/system_axi_ad9371_rx_os_clkgen_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_os_xcvr_0/sim/system_axi_ad9371_rx_os_xcvr_0.v" \
    "$ref_dir/../../../bd/system/ip/system_util_ad9371_rx_os_cpack_0/sim/system_util_ad9371_rx_os_cpack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_os_dma_0/sim/system_axi_ad9371_rx_os_dma_0.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_datafmt.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/ad_dcfilter.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_dds.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_dds_1.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_dds_sine.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_iqcor.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/xilinx/common/ad_mul.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/ad_xcvr_rx_if.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371_if.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371_rx.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371_rx_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371_rx_os.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371_tx.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371_tx_channel.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_adc_channel.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_adc_common.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_clock_mon.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_dac_channel.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_dac_common.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_xfer_cntrl.v" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/github/hdl-hdl_2018_r1/library/common/up_xfer_status.v" \
    "$ref_dir/../../../bd/system/ipshared/a0b9/axi_ad9371.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_core_0/sim/system_axi_ad9371_core_0.v" \
    "$ref_dir/../../../bd/system/ipshared/bdee/util_adxcvr_xch.v" \
    "$ref_dir/../../../bd/system/ipshared/bdee/util_adxcvr_xcm.v" \
    "$ref_dir/../../../bd/system/ipshared/bdee/util_adxcvr.v" \
    "$ref_dir/../../../bd/system/ip/system_util_ad9371_xcvr_0/sim/system_util_ad9371_xcvr_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_tx_jesd_rstgen_0/sim/system_axi_ad9371_tx_jesd_rstgen_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_jesd_rstgen_0/sim/system_axi_ad9371_rx_jesd_rstgen_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9371_rx_os_jesd_rstgen_0/sim/system_axi_ad9371_rx_os_jesd_rstgen_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_sys_dma_rstgen_0/sim/system_sys_dma_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ipshared/a6ac/jesd204_up_common.v" \
    "$ref_dir/../../../bd/system/ipshared/a6ac/jesd204_up_sysref.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/jesd204_up_ilas_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/jesd204_up_rx.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/jesd204_up_rx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/axi_jesd204_rx.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_axi_1/sim/system_rx_axi_1.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/jesd204_eof_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/jesd204_lmfc.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/jesd204_scrambler.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/pipeline_stage.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/align_mux.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/elastic_buffer.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_ilas_monitor.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_lane_latency_monitor.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx_cgs.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx_ctrl.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_1/sim/system_rx_1.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_axi_0/sim/system_rx_axi_0.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_0/sim/system_rx_0.v" \
    "$ref_dir/../../../bd/system/ipshared/6105/jesd204_up_tx.v" \
    "$ref_dir/../../../bd/system/ipshared/6105/axi_jesd204_tx.v" \
    "$ref_dir/../../../bd/system/ip/system_tx_axi_0/sim/system_tx_axi_0.v" \
    "$ref_dir/../../../bd/system/ipshared/d343/jesd204_tx_ctrl.v" \
    "$ref_dir/../../../bd/system/ipshared/d343/jesd204_tx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/d343/jesd204_tx.v" \
    "$ref_dir/../../../bd/system/ip/system_tx_0/sim/system_tx_0.v" \
    "$ref_dir/../../../bd/system/ip/system_blk_mem_gen_0_0/sim/system_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_xbar_1/sim/system_xbar_1.v" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_and.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_or.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_0_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_0_clk_ibuf.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_0_infrastructure.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_0_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_arb_mux.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_arb_row_col.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_arb_select.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_bank_cntrl.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_bank_common.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_bank_compare.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_bank_mach.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_bank_queue.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_bank_state.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_col_mach.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_mc.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_rank_cntrl.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_rank_common.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_rank_mach.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_0_round_robin_arb.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_0_ecc_buf.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_0_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_0_ecc_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_0_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_0_fi_xor.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v4_0_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v4_0_mem_intfc.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_calib_top.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_init.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_top.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_poc_cc.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_poc_edge_store.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_poc_meta.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_poc_pd.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_poc_tap_base.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_0_poc_top.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_0_ui_cmd.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_0_ui_rd_data.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_0_ui_top.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_0_ui_wr_data.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/system_mig_7series_0_1_mig_sim.v" \
    "$ref_dir/../../../bd/system/ip/system_mig_7series_0_1_1/system_mig_7series_0_1/user_design/rtl/system_mig_7series_0_1.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/445f/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_auto_cc_0/sim/system_auto_cc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/1cdc/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adrv9371x_kcu105.srcs/sources_1/bd/system/ipshared/225a" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_cc_df_2/sim/system_auto_us_cc_df_2.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_cc_df_1/sim/system_auto_us_cc_df_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_cc_df_0/sim/system_auto_us_cc_df_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_6/sim/system_auto_us_df_6.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_5/sim/system_auto_us_df_5.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_4/sim/system_auto_us_df_4.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_3/sim/system_auto_us_df_3.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_2/sim/system_auto_us_df_2.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_1/sim/system_auto_us_df_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_df_0/sim/system_auto_us_df_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_0_0/sim/system_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_1_0/sim/system_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_2_0/sim/system_tier2_xbar_2_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
